name: GitHub Actions Demo
on:
  workflow_dispatch:
    inputs:
          environment:
            description: 'Environment to deploy to'
            type: environment
            required: true
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron:  '15 6 * * 0'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Name:" ${{ github.event_name }} 
      - run: echo "Branch:" ${{ github.ref }} 
      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "Files:"
          tree
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "Testing"
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "Testing"
          sleep 15
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "1"
          sleep 15
      - run: |
          echo "2"
          sleep 15
      - run: |
          echo "3"
          sleep 15
      - run: |
          echo "4"
          sleep 15
      - run: |
          echo "5"
          sleep 15
